### ISSUE TITLE
unable to connect mqtt over tls

### ISSUE THREAD

**Issue by himadrinath** [emitter-io/csharp#15]
unable to connect using tls. in node project its working like this

`require('emitter-io').connect( {host: 'myhost.com', port: 443 , secure: true });`

passing secure options but in C# connection has 3 parameters broker, brokerPort, defaultkey

how can i connect?

**Comment by Florimond** [comment]
I suppose you installed the nugget and for some reason it wasn't updated.

The source code currently has these 4 constructors:

https://github.com/emitter-io/csharp/blob/2d68e4ba7926cfcd7c339f59d4fcc8bcb65720f0/Emitter/Emitter.cs#L65

You can either use the source code directly, or wait for us to look into this nugget update issue.

**Comment by himadrinath** [comment]
my version : 1.0.41

**Comment by himadrinath** [comment]
in this line using [TLSv1_0](https://github.com/emitter-io/csharp/blob/2d68e4ba7926cfcd7c339f59d4fcc8bcb65720f0/Emitter/Emitter.cs#L100) but mine is TLSv1_2 how can i change it..

**Comment by himadrinath** [comment]
@Florimond after using source code directly getting this

```
Unhandled Exception: System.ArgumentException: Library compiled without SSL support
   at Emitter.MqttClient.Init(String brokerHostName, Int32 brokerPort, Boolean secure, X509Certificate caCert, X509Certificate clientCert, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback) in C:\Users\Himadri\Documents\Visual Studio 2017\Projects\Emitter_test\Emitter\MqttClient.cs:line 355
   at Emitter.MqttClient..ctor(String brokerHostName, Int32 brokerPort, Boolean secure, X509Certificate caCert, X509Certificate clientCert, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback) in C:\Users\Himadri\Documents\Visual Studio 2017\Projects\Emitter_test\Emitter\MqttClient.cs:line 319
   at Emitter.MqttClient..ctor(String brokerHostName, Int32 brokerPort, Boolean secure, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback) in C:\Users\Himadri\Documents\Visual Studio 2017\Projects\Emitter_test\Emitter\MqttClient.cs:line 300
   at Emitter.Connection..ctor(String defaultKey, String broker, Int32 brokerPort, Boolean secure) in C:\Users\Himadri\Documents\Visual Studio 2017\Projects\Emitter_test\Emitter\Emitter.cs:line 98
   at Emitter.Connection.Establish(String defaultKey, String broker, Int32 brokerPort, Boolean secure) in C:\Users\Himadri\Documents\Visual Studio 2017\Projects\Emitter_test\Emitter\Emitter.cs:line 176
```

**Comment by Florimond** [comment]
The Emitter project needs to be build with "SSL".

![image](https://user-images.githubusercontent.com/372102/65414260-a108a300-ddf3-11e9-87c9-adce623cbda8.png)

**Comment by himadrinath** [comment]
@Florimond if i use SSL getting error if i use Fx getting error
On using SSL

![Emitter_SSL_2019-09-23 185213](https://user-images.githubusercontent.com/12247490/65429199-6b83aa00-de33-11e9-89ac-2ad00fcd7c19.jpg)

and using FX

![Emitter_Fx_2019-09-23 185304](https://user-images.githubusercontent.com/12247490/65429245-7b9b8980-de33-11e9-907f-84f0d25a015c.jpg)
